In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('BankChurners_cleaned.csv')

In [3]:
df.head()

Attrition_Flag  Customer_Age Gender  Dependent_count Education_Level  \
0  Existing Customer            45      M                3     High School   
1  Existing Customer            49      F                5        Graduate   
2  Existing Customer            51      M                3        Graduate   
3  Existing Customer            40      F                4     High School   
4  Existing Customer            40      M                3      Uneducated   

  Marital_Status Income_Category Card_Category  Months_on_book  \
0        Married     $60K - $80K          Blue              39   
1         Single  Less than $40K          Blue              44   
2        Married    $80K - $120K          Blue              36   
3        Unknown  Less than $40K          Blue              34   
4        Married     $60K - $80K          Blue              21   

   Total_Relationship_Count  Months_Inactive_12_mon  Contacts_Count_12_mon  \
0                         5                       1                      3   
1                         6                       1                      2   
2                         4                       1                      0   
3                         3                       4                      1   
4                         5                       1                      0   

   Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0       12691.0                  777          11914.0                 1.335   
1        8256.0                  864           7392.0                 1.541   
2        3418.0                    0           3418.0                 2.594   
3        3313.0                 2517            796.0                 1.405   
4        4716.0                    0           4716.0                 2.175   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0             1144              42                1.625                  0.061  
1             1291              33                3.714                  0.105  
2             1887              20                2.333                  0.000  
3             1171              20                2.333                  0.760  
4              816              28                2.500                  0.000

In [4]:
df.shape

(10127, 20)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Attrition_Flag            10127 non-null  object 
 1   Customer_Age              10127 non-null  int64  
 2   Gender                    10127 non-null  object 
 3   Dependent_count           10127 non-null  int64  
 4   Education_Level           10127 non-null  object 
 5   Marital_Status            10127 non-null  object 
 6   Income_Category           10127 non-null  object 
 7   Card_Category             10127 non-null  object 
 8   Months_on_book            10127 non-null  int64  
 9   Total_Relationship_Count  10127 non-null  int64  
 10  Months_Inactive_12_mon    10127 non-null  int64  
 11  Contacts_Count_12_mon     10127 non-null  int64  
 12  Credit_Limit              10127 non-null  float64
 13  Total_Revolving_Bal       10127 non-null  int64  
 14  Avg_Op

In [6]:
df.isnull().sum()

Attrition_Flag              0
Customer_Age                0
Gender                      0
Dependent_count             0
Education_Level             0
Marital_Status              0
Income_Category             0
Card_Category               0
Months_on_book              0
Total_Relationship_Count    0
Months_Inactive_12_mon      0
Contacts_Count_12_mon       0
Credit_Limit                0
Total_Revolving_Bal         0
Avg_Open_To_Buy             0
Total_Amt_Chng_Q4_Q1        0
Total_Trans_Amt             0
Total_Trans_Ct              0
Total_Ct_Chng_Q4_Q1         0
Avg_Utilization_Ratio       0
dtype: int64

# X & Y split

In [7]:
X = df.drop('Attrition_Flag', axis=1)
X.head()

Customer_Age Gender  Dependent_count Education_Level Marital_Status  \
0            45      M                3     High School        Married   
1            49      F                5        Graduate         Single   
2            51      M                3        Graduate        Married   
3            40      F                4     High School        Unknown   
4            40      M                3      Uneducated        Married   

  Income_Category Card_Category  Months_on_book  Total_Relationship_Count  \
0     $60K - $80K          Blue              39                         5   
1  Less than $40K          Blue              44                         6   
2    $80K - $120K          Blue              36                         4   
3  Less than $40K          Blue              34                         3   
4     $60K - $80K          Blue              21                         5   

   Months_Inactive_12_mon  Contacts_Count_12_mon  Credit_Limit  \
0                       1                      3       12691.0   
1                       1                      2        8256.0   
2                       1                      0        3418.0   
3                       4                      1        3313.0   
4                       1                      0        4716.0   

   Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0                  777          11914.0                 1.335   
1                  864           7392.0                 1.541   
2                    0           3418.0                 2.594   
3                 2517            796.0                 1.405   
4                    0           4716.0                 2.175   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0             1144              42                1.625                  0.061  
1             1291              33                3.714                  0.105  
2             1887              20                2.333                  0.000  
3             1171              20                2.333                  0.760  
4              816              28                2.500                  0.000

In [8]:
Y = df['Attrition_Flag']
Y.head()

0    Existing Customer
1    Existing Customer
2    Existing Customer
3    Existing Customer
4    Existing Customer
Name: Attrition_Flag, dtype: object

In [9]:
X.shape, Y.shape

((10127, 19), (10127,))

In [10]:
X.dtypes

Customer_Age                  int64
Gender                       object
Dependent_count               int64
Education_Level              object
Marital_Status               object
Income_Category              object
Card_Category                object
Months_on_book                int64
Total_Relationship_Count      int64
Months_Inactive_12_mon        int64
Contacts_Count_12_mon         int64
Credit_Limit                float64
Total_Revolving_Bal           int64
Avg_Open_To_Buy             float64
Total_Amt_Chng_Q4_Q1        float64
Total_Trans_Amt               int64
Total_Trans_Ct                int64
Total_Ct_Chng_Q4_Q1         float64
Avg_Utilization_Ratio       float64
dtype: object

In [11]:
X_ohe = pd.get_dummies(X)

In [12]:
X_ohe.shape

(10127, 37)

In [13]:
X_ohe.dtypes

Customer_Age                        int64
Dependent_count                     int64
Months_on_book                      int64
Total_Relationship_Count            int64
Months_Inactive_12_mon              int64
Contacts_Count_12_mon               int64
Credit_Limit                      float64
Total_Revolving_Bal                 int64
Avg_Open_To_Buy                   float64
Total_Amt_Chng_Q4_Q1              float64
Total_Trans_Amt                     int64
Total_Trans_Ct                      int64
Total_Ct_Chng_Q4_Q1               float64
Avg_Utilization_Ratio             float64
Gender_F                             bool
Gender_M                             bool
Education_Level_College              bool
Education_Level_Doctorate            bool
Education_Level_Graduate             bool
Education_Level_High School          bool
Education_Level_Post-Graduate        bool
Education_Level_Uneducated           bool
Education_Level_Unknown              bool
Marital_Status_Divorced           

# Format the target Y

In [14]:
Y.dtypes

dtype('O')

In [15]:
Y.value_counts()

Attrition_Flag
Existing Customer    8500
Attrited Customer    1627
Name: count, dtype: int64

In [16]:
Y.loc[Y=='Existing Customer',] = 0
Y.loc[Y=='Attrited Customer',] = 1

C:\Users\alish\AppData\Local\Temp\ipykernel_16068\162720568.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Y.loc[Y=='Existing Customer',] = 0
C:\Users\alish\AppData\Local\Temp\ipykernel_16068\162720568.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Y.loc[Y=='Attrited Customer',] = 1


In [17]:
Y.unique()

array([0, 1], dtype=object)

In [18]:
Y.nunique()

2

In [19]:
Y.dtype

dtype('O')

In [20]:
Y = Y.astype('int')

In [21]:
Y.dtype

dtype('int32')

# train test split

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_ohe, Y, test_size=0.3, random_state=7, stratify=Y)

In [23]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((7088, 37), (3039, 37), (7088,), (3039,))

# Feature selection

# using PCA

In [24]:
from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import SelectFromModel

In [25]:
pca = PCA(n_components = 0.95, random_state=7)

In [26]:
pca.fit(X_train)
# Y_train is not included bcoz it's unsupervised learning

PCA(n_components=0.95, random_state=7)

In [27]:
pca.n_components_

2

In [28]:
pca.components_

array([[-4.41556492e-06,  6.55675570e-06,  2.09981677e-06,
        -9.55978495e-06, -2.06770849e-06,  1.73570764e-06,
         7.06282944e-01,  2.63307700e-04,  7.06019637e-01,
         2.64859960e-07,  5.19670528e-02,  1.73794961e-04,
         1.06663245e-07, -1.09710508e-05, -1.64360945e-05,
         1.64360945e-05,  5.54770813e-08, -8.27373601e-08,
         2.13503378e-07, -3.10100158e-07, -8.35640313e-08,
         3.75900779e-07, -1.68479689e-07,  4.84754533e-07,
        -1.76435711e-06,  5.87856547e-07,  6.91746031e-07,
         6.57914760e-06, -4.86362139e-06,  2.73010517e-06,
         9.40660025e-06, -1.48574480e-05,  1.00521633e-06,
        -9.67559703e-06,  1.88327836e-06,  3.69557805e-07,
         7.42276086e-06],
       [-9.71492117e-05,  1.73754036e-06, -8.45443827e-05,
        -1.52911763e-04, -1.23918273e-05, -3.95586365e-05,
        -2.71927501e-02,  1.90977805e-02, -4.62905306e-02,
         2.62781994e-06,  9.98359326e-01,  5.62407449e-03,
         6.20920797e-06,  1.40

In [29]:
X_train_pca = pca.transform(X_train)
X_test_pca = pca.transform(X_test)

# decision tree

In [30]:
dt = DecisionTreeClassifier(criterion='gini', random_state=7, class_weight='balanced')

In [31]:
dt.fit(X_train, Y_train)
# Y_train is included here bcoz it's supervised learning

DecisionTreeClassifier(class_weight='balanced', random_state=7)

In [32]:
dt.feature_importances_

array([2.22677432e-02, 7.10129157e-03, 1.01156158e-02, 5.29637201e-02,
       8.37384226e-03, 9.93388980e-03, 1.61128035e-02, 9.25636572e-02,
       1.15737642e-02, 4.92337588e-02, 1.84691256e-01, 4.37071796e-01,
       6.23269520e-02, 8.05915776e-03, 3.80152009e-17, 1.94628404e-03,
       8.29226640e-05, 1.12665855e-03, 3.16022332e-04, 4.63931999e-04,
       1.44208440e-04, 1.45691429e-03, 1.22846478e-03, 2.18123452e-03,
       4.25354006e-03, 2.82167043e-04, 2.14568256e-03, 2.99342072e-04,
       3.47412673e-03, 1.34998065e-03, 2.80124896e-03, 2.82167043e-04,
       1.43856556e-03, 0.00000000e+00, 0.00000000e+00, 1.72918322e-03,
       6.08106773e-04])

In [33]:
feature_tup = tuple(zip(X_train.columns, dt.feature_importances_))

In [34]:
sorted(feature_tup, key = lambda x : -x[1])

[('Total_Trans_Ct', 0.4370717956080788),
 ('Total_Trans_Amt', 0.18469125596809555),
 ('Total_Revolving_Bal', 0.09256365715486943),
 ('Total_Ct_Chng_Q4_Q1', 0.062326951962327244),
 ('Total_Relationship_Count', 0.05296372005210665),
 ('Total_Amt_Chng_Q4_Q1', 0.04923375881705681),
 ('Customer_Age', 0.02226774323240459),
 ('Credit_Limit', 0.016112803470415975),
 ('Avg_Open_To_Buy', 0.011573764246454798),
 ('Months_on_book', 0.010115615799537006),
 ('Contacts_Count_12_mon', 0.00993388980238585),
 ('Months_Inactive_12_mon', 0.008373842255208588),
 ('Avg_Utilization_Ratio', 0.008059157763627244),
 ('Dependent_count', 0.007101291570407155),
 ('Marital_Status_Married', 0.0042535400623745735),
 ('Income_Category_$40K - $60K', 0.0034741267345907326),
 ('Income_Category_$80K - $120K', 0.002801248962349818),
 ('Marital_Status_Divorced', 0.0021812345177598734),
 ('Marital_Status_Unknown', 0.00214568256095734),
 ('Gender_M', 0.001946284044892295),
 ('Card_Category_Platinum', 0.0017291832232415295),
 

In [35]:
sel = SelectFromModel(DecisionTreeClassifier(criterion='gini', random_state=7, class_weight='balanced'),threshold='mean')

In [46]:
sel.fit(X_train, Y_train)

SelectFromModel(estimator=DecisionTreeClassifier(class_weight='balanced',
                                                 random_state=7),
                threshold='mean')

In [47]:
sel.get_feature_names_out

<bound method SelectorMixin.get_feature_names_out of SelectFromModel(estimator=DecisionTreeClassifier(class_weight='balanced',
                                                 random_state=7),
                threshold='mean')>

In [48]:
X_train_DT = sel.transform(X_train)

In [49]:
X_test_DT = sel.transform(X_test)

In [50]:
sel.get_feature_names_out(X_train.columns)

array(['Total_Relationship_Count', 'Total_Revolving_Bal',
       'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt', 'Total_Trans_Ct',
       'Total_Ct_Chng_Q4_Q1'], dtype=object)

In [51]:
sel.estimator_.feature_importances_

array([2.22677432e-02, 7.10129157e-03, 1.01156158e-02, 5.29637201e-02,
       8.37384226e-03, 9.93388980e-03, 1.61128035e-02, 9.25636572e-02,
       1.15737642e-02, 4.92337588e-02, 1.84691256e-01, 4.37071796e-01,
       6.23269520e-02, 8.05915776e-03, 3.80152009e-17, 1.94628404e-03,
       8.29226640e-05, 1.12665855e-03, 3.16022332e-04, 4.63931999e-04,
       1.44208440e-04, 1.45691429e-03, 1.22846478e-03, 2.18123452e-03,
       4.25354006e-03, 2.82167043e-04, 2.14568256e-03, 2.99342072e-04,
       3.47412673e-03, 1.34998065e-03, 2.80124896e-03, 2.82167043e-04,
       1.43856556e-03, 0.00000000e+00, 0.00000000e+00, 1.72918322e-03,
       6.08106773e-04])

In [52]:
X_train.columns

Index(['Customer_Age', 'Dependent_count', 'Months_on_book',
       'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio',
       'Gender_F', 'Gender_M', 'Education_Level_College',
       'Education_Level_Doctorate', 'Education_Level_Graduate',
       'Education_Level_High School', 'Education_Level_Post-Graduate',
       'Education_Level_Uneducated', 'Education_Level_Unknown',
       'Marital_Status_Divorced', 'Marital_Status_Married',
       'Marital_Status_Single', 'Marital_Status_Unknown',
       'Income_Category_$120K +', 'Income_Category_$40K - $60K',
       'Income_Category_$60K - $80K', 'Income_Category_$80K - $120K',
       'Income_Category_Less than $40K', 'Income_Category_Unknown',
       'Card_Category_Blue', 'Card_Category_Gold', 'Card_Category_Platinum',
       'Car

# RFE Recursive Feature Selection

In [53]:
from sklearn.feature_selection import RFE

In [54]:
rfe = RFE(DecisionTreeClassifier(criterion='gini',random_state=7,class_weight='balanced'),
          n_features_to_select =0.5)

In [55]:
rfe.fit(X_train,Y_train)

RFE(estimator=DecisionTreeClassifier(class_weight='balanced', random_state=7),
    n_features_to_select=0.5)

In [56]:
rfe.ranking_

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 12,  3, 15,
        7, 17, 11, 18,  6,  9,  2,  1, 10,  5, 14,  1,  8,  1, 16,  4, 19,
       20,  1, 13])